#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

JENKINS_TESTS_DIR="$DIR/jenkins-tests"
LOCKFILE="/tmp/adam-jenkins-test.lock"

lockfile -r -1 $LOCKFILE || exit 1
# Pass the project root by environment variable to scripts
export PROJECT_ROOT="$DIR/.."
$JENKINS_TESTS_DIR/0000-test-script
rm -f $LOCKFILE 
